formatter: markdown table

sections:
  hide-all: true
  show:
    - requirements
    - inputs
    - outputs

sort:
  enabled: true
  by:
    - required

settings:
  indent: 2
  required: true
  sensitive: true
